version: "3.1"

services:
    postgres:
        image: "postgres:15-alpine"
        volumes:
            - "./docker/postgresql:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "postgre"
            POSTGRES_PASSWORD: "postgre"
            LANG: "ru_RU.utf8"
            POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru-RU"
        ports:
            - "5432:5432"

    nginx:
        image: "nginx:alpine"
        volumes:
            - "./:/var/www/html"
            - "./docker/logs/nginx:/var/log/nginx"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"

    php:
        build: docker/php
        volumes:
            - "./:/var/www/html"
            - "./docker/logs/php/:/var/log/php-fpm"
            - "./docker/php/php.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini"
