###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    php_postgres:
        image: 'postgres:15-alpine'
        container_name: php_postgres
        working_dir: /application
        volumes:
            - './docker_var/pgdata:/var/lib/postgresql/data'
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - DB_HOST=${DATABASE_HOST}
            - POSTGRES_DB=${DATABASE_NAME}
            - LANG=ru_RU.utf8
            - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=ru-RU
        ports:
            - '5432:5432'

    webserver:
        image: 'nginx:alpine'
        container_name: php_nginx
        working_dir: /application
        volumes:
            - './public/bundles:/application/public/bundles'
            - './docker_var/logs/nginx:/var/log/nginx'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '53000:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: php_fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker_var/logs/php-fpm:/var/log/php-fpm'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
